//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int ID { get; set; }
        public string Access_LVL { get; set; }
        public int ID_UserRoom { get; set; }
    
        public virtual UserRoom UserRoom { get; set; }
    }
}
