//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public System.Guid ID_FILE { get; set; }
        public byte[] fileData { get; set; }
        public string cfg { get; set; }
        public Nullable<int> is_current { get; set; }
        public int ID { get; set; }
    }
}
