//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Option()
        {
            this.ID = 1;
            this.Time_Series = new HashSet<Time_Series>();
        }
    
        public int ID { get; set; }
        public string Type_Option { get; set; }
        public int ID_Quantity { get; set; }
        public int ID_Sensor { get; set; }
    
        public virtual Quantity Quantity { get; set; }
        public virtual Sensor Sensor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Time_Series> Time_Series { get; set; }
    }
}
