//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sensor()
        {
            this.Options = new HashSet<Option>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string C_Group { get; set; }
        public string Status { get; set; }
        public int ID_TYPE { get; set; }
        public Nullable<int> ID_Thing { get; set; }
        public Nullable<int> ID_RoomModel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Options { get; set; }
        public virtual RoomModel RoomModel { get; set; }
        public virtual Sensor_Type Sensor_Type { get; set; }
        public virtual Thing Thing { get; set; }
    }
}
