//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thing()
        {
            this.Sensors = new HashSet<Sensor>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ID_Model { get; set; }
        public int ID_RoomModel { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual RoomModel RoomModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sensor> Sensors { get; set; }
    }
}
