//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time_Series
    {
        public string Value { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ID_Option { get; set; }
        public int ID { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
