name: OmnySync-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  TestTaskCreationProcess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install git+https://github.com/c0j0s/notion-py@master#egg=notion

      - name: Run Tests
        run: |
          cd ./OmnySync.Script/data
          python -m unittest -v tests/tests_TaskCreationProcess.py

  TestTaskProccesses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install git+https://github.com/c0j0s/notion-py@master#egg=notion

      - name: Run Tests
        run: |
          cd ./OmnySync.Script/data
          python -m unittest -v tests/tests_TaskProccesses.py
        

  PROD:
    runs-on: ubuntu-latest
    needs: [TestTaskCreationProcess, TestTaskProccesses] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload files to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          name: OmnySync.Script
          target: ./OmnySync.Script
          credentials: ${{ secrets.GOOGLE_CRED }}
          folder: ${{ secrets.FOLDER_ID }}




