//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Access.
    /// </summary>
    // *** Start programmer edit section *** (Access CustomAttributes)

    // *** End programmer edit section *** (Access CustomAttributes)
    [PublishName("Уровень доступа")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SMC_AccessE", new string[] {
            "AccessLevel as \'Уровень доступа\'",
            "Room as \'Помещения\'",
            "Room.Name as \'Наименование\'",
            "User as \'Пользователь\'",
            "User.Login as \'Имя пользователя\'"})]
    [View("SMC_AccessL", new string[] {
            "AccessLevel as \'Уровень доступа\'",
            "Room.Name as \'Наименование\'",
            "User.Login as \'Имя пользователя\'"})]
    public class Access : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Product_4858.TypeAccess fAccessLevel;
        
        private IIS.Product_4858.Room fRoom;
        
        private IIS.Product_4858.User fUser;
        
        // *** Start programmer edit section *** (Access CustomMembers)

        // *** End programmer edit section *** (Access CustomMembers)

        
        /// <summary>
        /// AccessLevel.
        /// </summary>
        // *** Start programmer edit section *** (Access.AccessLevel CustomAttributes)

        // *** End programmer edit section *** (Access.AccessLevel CustomAttributes)
        [PublishName("Уровень доступа")]
        public virtual IIS.Product_4858.TypeAccess AccessLevel
        {
            get
            {
                // *** Start programmer edit section *** (Access.AccessLevel Get start)

                // *** End programmer edit section *** (Access.AccessLevel Get start)
                IIS.Product_4858.TypeAccess result = this.fAccessLevel;
                // *** Start programmer edit section *** (Access.AccessLevel Get end)

                // *** End programmer edit section *** (Access.AccessLevel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Access.AccessLevel Set start)

                // *** End programmer edit section *** (Access.AccessLevel Set start)
                this.fAccessLevel = value;
                // *** Start programmer edit section *** (Access.AccessLevel Set end)

                // *** End programmer edit section *** (Access.AccessLevel Set end)
            }
        }
        
        /// <summary>
        /// Access.
        /// </summary>
        // *** Start programmer edit section *** (Access.Room CustomAttributes)

        // *** End programmer edit section *** (Access.Room CustomAttributes)
        [PropertyStorage(new string[] {
                "Room"})]
        [NotNull()]
        public virtual IIS.Product_4858.Room Room
        {
            get
            {
                // *** Start programmer edit section *** (Access.Room Get start)

                // *** End programmer edit section *** (Access.Room Get start)
                IIS.Product_4858.Room result = this.fRoom;
                // *** Start programmer edit section *** (Access.Room Get end)

                // *** End programmer edit section *** (Access.Room Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Access.Room Set start)

                // *** End programmer edit section *** (Access.Room Set start)
                this.fRoom = value;
                // *** Start programmer edit section *** (Access.Room Set end)

                // *** End programmer edit section *** (Access.Room Set end)
            }
        }
        
        /// <summary>
        /// Access.
        /// </summary>
        // *** Start programmer edit section *** (Access.User CustomAttributes)

        // *** End programmer edit section *** (Access.User CustomAttributes)
        [PropertyStorage(new string[] {
                "User"})]
        [NotNull()]
        public virtual IIS.Product_4858.User User
        {
            get
            {
                // *** Start programmer edit section *** (Access.User Get start)

                // *** End programmer edit section *** (Access.User Get start)
                IIS.Product_4858.User result = this.fUser;
                // *** Start programmer edit section *** (Access.User Get end)

                // *** End programmer edit section *** (Access.User Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Access.User Set start)

                // *** End programmer edit section *** (Access.User Set start)
                this.fUser = value;
                // *** Start programmer edit section *** (Access.User Set end)

                // *** End programmer edit section *** (Access.User Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SMC_AccessE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_AccessE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_AccessE", typeof(IIS.Product_4858.Access));
                }
            }
            
            /// <summary>
            /// "SMC_AccessL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_AccessL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_AccessL", typeof(IIS.Product_4858.Access));
                }
            }
        }
    }
}
