//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Organization.
    /// </summary>
    // *** Start programmer edit section *** (Organization CustomAttributes)

    // *** End programmer edit section *** (Organization CustomAttributes)
    [PublishName("Организация")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SMC_OrganizationE", new string[] {
            "Name as \'Наименование\'",
            "CountEmployee as \'Количество работников\'"})]
    [View("SMC_OrganizationL", new string[] {
            "Name as \'Наименование\'",
            "CountEmployee as \'Количество работников\'"})]
    public class Organization : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fCountEmployee;
        
        // *** Start programmer edit section *** (Organization CustomMembers)

        // *** End programmer edit section *** (Organization CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Organization.Name CustomAttributes)

        // *** End programmer edit section *** (Organization.Name CustomAttributes)
        [StrLen(255)]
        [PublishName("Наименование")]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Organization.Name Get start)

                // *** End programmer edit section *** (Organization.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Organization.Name Get end)

                // *** End programmer edit section *** (Organization.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Organization.Name Set start)

                // *** End programmer edit section *** (Organization.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Organization.Name Set end)

                // *** End programmer edit section *** (Organization.Name Set end)
            }
        }
        
        /// <summary>
        /// CountEmployee.
        /// </summary>
        // *** Start programmer edit section *** (Organization.CountEmployee CustomAttributes)

        // *** End programmer edit section *** (Organization.CountEmployee CustomAttributes)
        [PublishName("Количество работников")]
        public virtual int CountEmployee
        {
            get
            {
                // *** Start programmer edit section *** (Organization.CountEmployee Get start)

                // *** End programmer edit section *** (Organization.CountEmployee Get start)
                int result = this.fCountEmployee;
                // *** Start programmer edit section *** (Organization.CountEmployee Get end)

                // *** End programmer edit section *** (Organization.CountEmployee Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Organization.CountEmployee Set start)

                // *** End programmer edit section *** (Organization.CountEmployee Set start)
                this.fCountEmployee = value;
                // *** Start programmer edit section *** (Organization.CountEmployee Set end)

                // *** End programmer edit section *** (Organization.CountEmployee Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SMC_OrganizationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_OrganizationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_OrganizationE", typeof(IIS.Product_4858.Organization));
                }
            }
            
            /// <summary>
            /// "SMC_OrganizationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_OrganizationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_OrganizationL", typeof(IIS.Product_4858.Organization));
                }
            }
        }
    }
}
