//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Room.
    /// </summary>
    // *** Start programmer edit section *** (Room CustomAttributes)

    // *** End programmer edit section *** (Room CustomAttributes)
    [PublishName("Помещение")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SMC_RoomE", new string[] {
            "Name as \'Наименование\'",
            "Number as \'Номер\'",
            "Floor as \'Этаж\'",
            "Building as \'Здание\'",
            "Building.Type as \'Тип\'"})]
    [View("SMC_RoomL", new string[] {
            "Name as \'Наименование\'",
            "Number as \'Номер\'",
            "Floor as \'Этаж\'",
            "Building.Type as \'Тип\'"})]
    public class Room : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fNumber;
        
        private int fFloor;
        
        private IIS.Product_4858.Building fBuilding;
        
        // *** Start programmer edit section *** (Room CustomMembers)

        // *** End programmer edit section *** (Room CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Room.Name CustomAttributes)

        // *** End programmer edit section *** (Room.Name CustomAttributes)
        [StrLen(255)]
        [PublishName("Наименование")]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Room.Name Get start)

                // *** End programmer edit section *** (Room.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Room.Name Get end)

                // *** End programmer edit section *** (Room.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Name Set start)

                // *** End programmer edit section *** (Room.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Room.Name Set end)

                // *** End programmer edit section *** (Room.Name Set end)
            }
        }
        
        /// <summary>
        /// Number.
        /// </summary>
        // *** Start programmer edit section *** (Room.Number CustomAttributes)

        // *** End programmer edit section *** (Room.Number CustomAttributes)
        [PublishName("Номер")]
        public virtual int Number
        {
            get
            {
                // *** Start programmer edit section *** (Room.Number Get start)

                // *** End programmer edit section *** (Room.Number Get start)
                int result = this.fNumber;
                // *** Start programmer edit section *** (Room.Number Get end)

                // *** End programmer edit section *** (Room.Number Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Number Set start)

                // *** End programmer edit section *** (Room.Number Set start)
                this.fNumber = value;
                // *** Start programmer edit section *** (Room.Number Set end)

                // *** End programmer edit section *** (Room.Number Set end)
            }
        }
        
        /// <summary>
        /// Floor.
        /// </summary>
        // *** Start programmer edit section *** (Room.Floor CustomAttributes)

        // *** End programmer edit section *** (Room.Floor CustomAttributes)
        [PublishName("Этаж")]
        public virtual int Floor
        {
            get
            {
                // *** Start programmer edit section *** (Room.Floor Get start)

                // *** End programmer edit section *** (Room.Floor Get start)
                int result = this.fFloor;
                // *** Start programmer edit section *** (Room.Floor Get end)

                // *** End programmer edit section *** (Room.Floor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Floor Set start)

                // *** End programmer edit section *** (Room.Floor Set start)
                this.fFloor = value;
                // *** Start programmer edit section *** (Room.Floor Set end)

                // *** End programmer edit section *** (Room.Floor Set end)
            }
        }
        
        /// <summary>
        /// Room.
        /// </summary>
        // *** Start programmer edit section *** (Room.Building CustomAttributes)

        // *** End programmer edit section *** (Room.Building CustomAttributes)
        [PropertyStorage(new string[] {
                "Building"})]
        [NotNull()]
        public virtual IIS.Product_4858.Building Building
        {
            get
            {
                // *** Start programmer edit section *** (Room.Building Get start)

                // *** End programmer edit section *** (Room.Building Get start)
                IIS.Product_4858.Building result = this.fBuilding;
                // *** Start programmer edit section *** (Room.Building Get end)

                // *** End programmer edit section *** (Room.Building Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Room.Building Set start)

                // *** End programmer edit section *** (Room.Building Set start)
                this.fBuilding = value;
                // *** Start programmer edit section *** (Room.Building Set end)

                // *** End programmer edit section *** (Room.Building Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SMC_RoomE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_RoomE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_RoomE", typeof(IIS.Product_4858.Room));
                }
            }
            
            /// <summary>
            /// "SMC_RoomL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_RoomL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_RoomL", typeof(IIS.Product_4858.Room));
                }
            }
        }
    }
}
