//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Sensors.
    /// </summary>
    // *** Start programmer edit section *** (Sensors CustomAttributes)

    // *** End programmer edit section *** (Sensors CustomAttributes)
    [PublishName("Сенсор")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SMC_SensorsE", new string[] {
            "Name as \'Наименование\'",
            "Type as \'Тип\'",
            "OutputData as \'Выходной параметр\'",
            "Room as \'Помещение\'",
            "Room.Name as \'Наименование\'"})]
    [View("SMC_SensorsL", new string[] {
            "Name as \'Наименование\'",
            "Type as \'Тип\'",
            "OutputData as \'Выходной параметр\'",
            "Room.Name as \'Наименование\'"})]
    public class Sensors : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Product_4858.TypeSensor fType;
        
        private string fOutputData;
        
        private IIS.Product_4858.Room fRoom;
        
        // *** Start programmer edit section *** (Sensors CustomMembers)

        // *** End programmer edit section *** (Sensors CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Sensors.Name CustomAttributes)

        // *** End programmer edit section *** (Sensors.Name CustomAttributes)
        [StrLen(255)]
        [PublishName("Наименование")]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Sensors.Name Get start)

                // *** End programmer edit section *** (Sensors.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Sensors.Name Get end)

                // *** End programmer edit section *** (Sensors.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sensors.Name Set start)

                // *** End programmer edit section *** (Sensors.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Sensors.Name Set end)

                // *** End programmer edit section *** (Sensors.Name Set end)
            }
        }
        
        /// <summary>
        /// Type.
        /// </summary>
        // *** Start programmer edit section *** (Sensors.Type CustomAttributes)

        // *** End programmer edit section *** (Sensors.Type CustomAttributes)
        [PublishName("Тип")]
        public virtual IIS.Product_4858.TypeSensor Type
        {
            get
            {
                // *** Start programmer edit section *** (Sensors.Type Get start)

                // *** End programmer edit section *** (Sensors.Type Get start)
                IIS.Product_4858.TypeSensor result = this.fType;
                // *** Start programmer edit section *** (Sensors.Type Get end)

                // *** End programmer edit section *** (Sensors.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sensors.Type Set start)

                // *** End programmer edit section *** (Sensors.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (Sensors.Type Set end)

                // *** End programmer edit section *** (Sensors.Type Set end)
            }
        }
        
        /// <summary>
        /// OutputData.
        /// </summary>
        // *** Start programmer edit section *** (Sensors.OutputData CustomAttributes)

        // *** End programmer edit section *** (Sensors.OutputData CustomAttributes)
        [StrLen(255)]
        [PublishName("Выходной параметр")]
        public virtual string OutputData
        {
            get
            {
                // *** Start programmer edit section *** (Sensors.OutputData Get start)

                // *** End programmer edit section *** (Sensors.OutputData Get start)
                string result = this.fOutputData;
                // *** Start programmer edit section *** (Sensors.OutputData Get end)

                // *** End programmer edit section *** (Sensors.OutputData Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sensors.OutputData Set start)

                // *** End programmer edit section *** (Sensors.OutputData Set start)
                this.fOutputData = value;
                // *** Start programmer edit section *** (Sensors.OutputData Set end)

                // *** End programmer edit section *** (Sensors.OutputData Set end)
            }
        }
        
        /// <summary>
        /// Sensors.
        /// </summary>
        // *** Start programmer edit section *** (Sensors.Room CustomAttributes)

        // *** End programmer edit section *** (Sensors.Room CustomAttributes)
        [PropertyStorage(new string[] {
                "Room"})]
        [NotNull()]
        public virtual IIS.Product_4858.Room Room
        {
            get
            {
                // *** Start programmer edit section *** (Sensors.Room Get start)

                // *** End programmer edit section *** (Sensors.Room Get start)
                IIS.Product_4858.Room result = this.fRoom;
                // *** Start programmer edit section *** (Sensors.Room Get end)

                // *** End programmer edit section *** (Sensors.Room Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Sensors.Room Set start)

                // *** End programmer edit section *** (Sensors.Room Set start)
                this.fRoom = value;
                // *** Start programmer edit section *** (Sensors.Room Set end)

                // *** End programmer edit section *** (Sensors.Room Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SMC_SensorsE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_SensorsE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_SensorsE", typeof(IIS.Product_4858.Sensors));
                }
            }
            
            /// <summary>
            /// "SMC_SensorsL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_SensorsL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_SensorsL", typeof(IIS.Product_4858.Sensors));
                }
            }
        }
    }
}
