//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Type sensor.
    /// </summary>
    // *** Start programmer edit section *** (TypeSensor CustomAttributes)

    // *** End programmer edit section *** (TypeSensor CustomAttributes)
    public enum TypeSensor
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeSensor.Temperature CustomAttributes)

        // *** End programmer edit section *** (TypeSensor.Temperature CustomAttributes)
        Temperature,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeSensor.Pressure CustomAttributes)

        // *** End programmer edit section *** (TypeSensor.Pressure CustomAttributes)
        Pressure,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeSensor.Gas CustomAttributes)

        // *** End programmer edit section *** (TypeSensor.Gas CustomAttributes)
        Gas,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeSensor.Camera CustomAttributes)

        // *** End programmer edit section *** (TypeSensor.Camera CustomAttributes)
        Camera,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeSensor.Manipulation CustomAttributes)

        // *** End programmer edit section *** (TypeSensor.Manipulation CustomAttributes)
        Manipulation,
    }
}
