//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Type building.
    /// </summary>
    // *** Start programmer edit section *** (TypeBuilding CustomAttributes)

    // *** End programmer edit section *** (TypeBuilding CustomAttributes)
    public enum TypeBuilding
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeBuilding.NewBulding CustomAttributes)

        // *** End programmer edit section *** (TypeBuilding.NewBulding CustomAttributes)
        NewBulding,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeBuilding.Khrushchev CustomAttributes)

        // *** End programmer edit section *** (TypeBuilding.Khrushchev CustomAttributes)
        Khrushchev,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeBuilding.Cottege CustomAttributes)

        // *** End programmer edit section *** (TypeBuilding.Cottege CustomAttributes)
        Cottege,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeBuilding.SchoolBuilding CustomAttributes)

        // *** End programmer edit section *** (TypeBuilding.SchoolBuilding CustomAttributes)
        SchoolBuilding,
    }
}
