//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Type access.
    /// </summary>
    // *** Start programmer edit section *** (TypeAccess CustomAttributes)

    // *** End programmer edit section *** (TypeAccess CustomAttributes)
    public enum TypeAccess
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeAccess.Admin CustomAttributes)

        // *** End programmer edit section *** (TypeAccess.Admin CustomAttributes)
        Admin,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeAccess.Full CustomAttributes)

        // *** End programmer edit section *** (TypeAccess.Full CustomAttributes)
        Full,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeAccess.Partly CustomAttributes)

        // *** End programmer edit section *** (TypeAccess.Partly CustomAttributes)
        Partly,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TypeAccess.None CustomAttributes)

        // *** End programmer edit section *** (TypeAccess.None CustomAttributes)
        None,
    }
}
