//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_4858
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User.
    /// </summary>
    // *** Start programmer edit section *** (User CustomAttributes)

    // *** End programmer edit section *** (User CustomAttributes)
    [PublishName("Пользователь")]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SMC_UserE", new string[] {
            "Login as \'Имя пользователя\'",
            "Password as \'Пароль\'",
            "PlaceFunc as \'Должность\'",
            "Name as \'Имя\'",
            "SecondName as \'Фамилия\'",
            "FatherName as \'Отчество\'",
            "PhoneNumber as \'Номер телефона\'",
            "Email as \'Электронная почта\'",
            "Address as \'Адрес\'",
            "Address.City as \'Город\'",
            "Organization as \'Организация\'",
            "Organization.Name as \'Наименование\'"})]
    [View("SMC_UserL", new string[] {
            "Login as \'Имя пользователя\'",
            "Password as \'Пароль\'",
            "PlaceFunc as \'Должность\'",
            "Name as \'Имя\'",
            "SecondName as \'Фамилия\'",
            "FatherName as \'Отчество\'",
            "PhoneNumber as \'Номер телефона\'",
            "Email as \'Электронная почта\'",
            "Address.City as \'Город\'",
            "Organization.Name as \'Наименование\'"})]
    public class User : IIS.Product_4858.Man
    {
        
        private string fLogin;
        
        private string fPassword;
        
        private string fPlaceFunc;
        
        private IIS.Product_4858.Organization fOrganization;
        
        // *** Start programmer edit section *** (User CustomMembers)

        // *** End programmer edit section *** (User CustomMembers)

        
        /// <summary>
        /// Login.
        /// </summary>
        // *** Start programmer edit section *** (User.Login CustomAttributes)

        // *** End programmer edit section *** (User.Login CustomAttributes)
        [StrLen(255)]
        [PublishName("Имя пользователя")]
        public virtual string Login
        {
            get
            {
                // *** Start programmer edit section *** (User.Login Get start)

                // *** End programmer edit section *** (User.Login Get start)
                string result = this.fLogin;
                // *** Start programmer edit section *** (User.Login Get end)

                // *** End programmer edit section *** (User.Login Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Login Set start)

                // *** End programmer edit section *** (User.Login Set start)
                this.fLogin = value;
                // *** Start programmer edit section *** (User.Login Set end)

                // *** End programmer edit section *** (User.Login Set end)
            }
        }
        
        /// <summary>
        /// Password.
        /// </summary>
        // *** Start programmer edit section *** (User.Password CustomAttributes)

        // *** End programmer edit section *** (User.Password CustomAttributes)
        [StrLen(255)]
        [PublishName("Пароль")]
        public virtual string Password
        {
            get
            {
                // *** Start programmer edit section *** (User.Password Get start)

                // *** End programmer edit section *** (User.Password Get start)
                string result = this.fPassword;
                // *** Start programmer edit section *** (User.Password Get end)

                // *** End programmer edit section *** (User.Password Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Password Set start)

                // *** End programmer edit section *** (User.Password Set start)
                this.fPassword = value;
                // *** Start programmer edit section *** (User.Password Set end)

                // *** End programmer edit section *** (User.Password Set end)
            }
        }
        
        /// <summary>
        /// PlaceFunc.
        /// </summary>
        // *** Start programmer edit section *** (User.PlaceFunc CustomAttributes)

        // *** End programmer edit section *** (User.PlaceFunc CustomAttributes)
        [StrLen(255)]
        [PublishName("Должность")]
        public virtual string PlaceFunc
        {
            get
            {
                // *** Start programmer edit section *** (User.PlaceFunc Get start)

                // *** End programmer edit section *** (User.PlaceFunc Get start)
                string result = this.fPlaceFunc;
                // *** Start programmer edit section *** (User.PlaceFunc Get end)

                // *** End programmer edit section *** (User.PlaceFunc Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.PlaceFunc Set start)

                // *** End programmer edit section *** (User.PlaceFunc Set start)
                this.fPlaceFunc = value;
                // *** Start programmer edit section *** (User.PlaceFunc Set end)

                // *** End programmer edit section *** (User.PlaceFunc Set end)
            }
        }
        
        /// <summary>
        /// User.
        /// </summary>
        // *** Start programmer edit section *** (User.Address CustomAttributes)

        // *** End programmer edit section *** (User.Address CustomAttributes)
        [TypeUsage(typeof(IIS.Product_4858.Address))]
        [PropertyStorage(new string[] {
                "Address"})]
        public override IIS.Product_4858.Address Address
        {
            get
            {
                // *** Start programmer edit section *** (User.Address Get start)

                // *** End programmer edit section *** (User.Address Get start)
                IIS.Product_4858.Address result = ((IIS.Product_4858.Address)(base.Address));
                // *** Start programmer edit section *** (User.Address Get end)

                // *** End programmer edit section *** (User.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Address Set start)

                // *** End programmer edit section *** (User.Address Set start)
                base.Address = ((IIS.Product_4858.Address)(value));
                // *** Start programmer edit section *** (User.Address Set end)

                // *** End programmer edit section *** (User.Address Set end)
            }
        }
        
        /// <summary>
        /// User.
        /// </summary>
        // *** Start programmer edit section *** (User.Organization CustomAttributes)

        // *** End programmer edit section *** (User.Organization CustomAttributes)
        [PropertyStorage(new string[] {
                "Organization"})]
        [NotNull()]
        public virtual IIS.Product_4858.Organization Organization
        {
            get
            {
                // *** Start programmer edit section *** (User.Organization Get start)

                // *** End programmer edit section *** (User.Organization Get start)
                IIS.Product_4858.Organization result = this.fOrganization;
                // *** Start programmer edit section *** (User.Organization Get end)

                // *** End programmer edit section *** (User.Organization Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (User.Organization Set start)

                // *** End programmer edit section *** (User.Organization Set start)
                this.fOrganization = value;
                // *** Start programmer edit section *** (User.Organization Set end)

                // *** End programmer edit section *** (User.Organization Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SMC_UserE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_UserE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_UserE", typeof(IIS.Product_4858.User));
                }
            }
            
            /// <summary>
            /// "SMC_UserL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SMC_UserL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SMC_UserL", typeof(IIS.Product_4858.User));
                }
            }
        }
    }
}
