/*flexberryautogenerated="true"*/
namespace IIS.Product_4858
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class SMC_ManL : BaseListForm<Man>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public SMC_ManL() : base(Man.Views.SMC_ManL)
        {
            EditPage = SMC_ManE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Man/SMC_ManL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
